### ISSUE TITLE
[BUG] [HELP] RELOAD HTML

### ISSUE THREAD

**Issue by kaelendev** [0DLCode/syncparty#2]
Le problème est ici:
```js
function reloadData() {
  isRequestRoomFinished = false;
  isRequestFileFinished = false;
  getRooms();
  getFiles();
  while (!globalFiles || !globalRooms){}
  console.log(globalFiles);
}

function reload() {
  console.log('Reloading...');
  reloadData();
  showRooms();
  showFiles();
}
```
Lorsque je fais un reload dans le script, autant que je le fasse, la variable `globalFiles` n'est pas modifié (ni `globalRooms` mais ça c'est normal). Ce n'est que le ```<action="reload()">``` qui est effectif sur la variable `globalFiles`

**Comment by kaelendev** [comment]
- [x] Fixed in #adc0e34aed7bf844a40cf066d200a158b9daf3d8

**Comment by daisseur** [comment]
> Le problème est ici:
> ```js
> function reloadData() {
>   isRequestRoomFinished = false;
>   isRequestFileFinished = false;
>   getRooms();
>   getFiles();
>   while (!globalFiles || !globalRooms){}
>   console.log(globalFiles);
> }
> 
> function reload() {
>   console.log('Reloading...');
>   reloadData();
>   showRooms();
>   showFiles();
> }
> ```
> Lorsque je fais un reload dans le script, autant que je le fasse, la variable `globalFiles` n'est pas modifié (ni `globalRooms` mais ça c'est normal). Ce n'est que le ```<action="reload()">``` qui est effectif sur la variable `globalFiles`
